//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_dany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso
    {
        public int codigo_curso { get; set; }
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public string ciclo { get; set; }
        public string tipo { get; set; }
    }
}
